=== kanodiaayush/Prism/prism/classes/dtds/options.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : options.dtd
    Created on : July 15, 2005, 3:58 AM
    Last change: July 15, 2005, 3:58 AM
    Author     : Andrew Hinton
    Description:
        Document to describe the structure of an options file.
	This version is current for PRISM 2.1.dev9.simapmc4
-->

<!ELEMENT options (prism, model, properties, simulator, log)>

<!ELEMENT prism (#PCDATA)>
<!ATTLIST prism
	verbose (true|false) #REQUIRED
	fairness (true|false) #REQUIRED
	precomputation (true|false) #REQUIRED
	compact (true|false) #REQUIRED
	cuddMaxMem CDATA #REQUIRED
	cuddEpsilon CDATA #REQUIRED
	iterativeMethod (power|jacobi|gaussSeidel|jor|sor) #REQUIRED
	overRelaxation CDATA #REQUIRED
	backwards (true|false) #REQUIRED
	pseudo (true|false) #REQUIRED
	termination (relative|absolute) #REQUIRED
	maxIterations CDATA #REQUIRED
	terminationEpsilon CDATA #REQUIRED
	engine (mtbdd|sparse|hybrid) #REQUIRED
	hybridNumLevels CDATA #REQUIRED
	hybridMaxMemory CDATA #REQUIRED
	hybridSORLevels CDATA #REQUIRED
	hybridSORMaxMemory CDATA #REQUIRED>

<!ELEMENT model (editor, editor)>
<!ATTLIST model
	autoParse (true|false) #REQUIRED
	autoManual (true|false) #REQUIRED
	parseDelay CDATA #REQUIRED
	>

<!ELEMENT editor ((regEx)*)>
<!ATTLIST editor
	fontName CDATA #REQUIRED
	fontStyle CDATA #REQUIRED
	fontSize CDATA #REQUIRED
        fontColourR CDATA #REQUIRED
	fontColourG CDATA #REQUIRED
	fontColourB CDATA #REQUIRED
	bgColourR CDATA #REQUIRED
	bgColourG CDATA #REQUIRED
	bgColourB CDATA #REQUIRED>

<!ELEMENT regEx (#PCDATA)>
<!ATTLIST regEx
	description CDATA #REQUIRED
	expression CDATA #REQUIRED
	colourR CDATA #REQUIRED
	colourG CDATA #REQUIRED
	colourB CDATA #REQUIRED
	style CDATA #REQUIRED
	>
	
<!ELEMENT properties (#PCDATA)>
<!ATTLIST properties
	fontName CDATA #REQUIRED
	fontStyle CDATA #REQUIRED
	fontSize CDATA #REQUIRED
	selectionColourR CDATA #REQUIRED
	selectionColourG CDATA #REQUIRED
	selectionColourB CDATA #REQUIRED
	warningColourR CDATA #REQUIRED
	warningColourG CDATA #REQUIRED
	warningColourB CDATA #REQUIRED
	additionStrategy (warn|never) #REQUIRED
	clearListOnLoad (true|false) #REQUIRED>

<!ELEMENT simulator (#PCDATA)>
<!ATTLIST simulator
	engine (prism|apmc) #REQUIRED
	simultaneous (true|false) #REQUIRED
	apmcStrategy CDATA #REQUIRED
	newPathAskDefault (true|false) #REQUIRED
	renderAllValues (true|false) #REQUIRED>
	
<!ELEMENT log (#PCDATA)>
<!ATTLIST log 
	fontName CDATA #REQUIRED
	fontStyle CDATA #REQUIRED
	fontSize CDATA #REQUIRED
	selectionColourR CDATA #REQUIRED
	selectionColourG CDATA #REQUIRED
	selectionColourB CDATA #REQUIRED
	bgColourR CDATA #REQUIRED
	bgColourG CDATA #REQUIRED
	bgColourB CDATA #REQUIRED 
	bufferLength CDATA #REQUIRED>

=== kanodiaayush/Prism/classes/config/currentOptions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE options SYSTEM "options.dtd">
<options>
<prism verbose="false" fairness="false" precomputation="true" compact="true" cuddMaxMem="204800" cuddEpsilon="1.0E-15" iterativeMethod="jacobi" overRelaxation="0.9" backwards="false" pseudo="false" termination="relative" maxIterations="10000" terminationEpsilon="1.0E-6" engine="hybrid" hybridNumLevels="-1" hybridMaxMemory="1024" hybridSORLevels="-1" hybridSORMaxMemory="1024"/>
<model autoParse="true" autoManual="true" parseDelay="1000">
<editor fontName="monospaced" fontStyle="0" fontSize="12" fontColourR="0" fontColourG="0" fontColourB="0" bgColourR="255" bgColourG="255" bgColourB="255">
<regEx description="Numeric" expression="\.|[0-9]" colourR="0" colourG="51" colourB="255" style="Plain"/>
<regEx description="Variable" expression="&#10;[A-Za-z_][A-Za-z0-9_]*|[A-Za-z_][A-Za-z0-9_]*|&#10;[A-Za-z_][A-Za-z0-9_]&#10;|&#10;[A-Za-z_][A-Za-z0-9_]" colourR="255" colourG="0" colourB="0" style="Plain"/>
<regEx description="Prism Keyword" expression="(\b|\p{Punct})(probabilistic|false|nondeterministic|stochastic|dtmc|mdp|ctmc|bool|int|double|const|formula|module|endmodule|true|false|global|init|prob|rate|min|max|system|endsystem|costs|endcosts|rewards|endrewards)(\b|\p{Punct})" colourR="0" colourG="0" colourB="0" style="Bold"/>
<regEx description="Single Line Comment" expression="//.*" colourR="0" colourG="99" colourB="0" style="Italic"/>
</editor>
<editor fontName="monospaced" fontStyle="0" fontSize="12" fontColourR="72" fontColourG="61" fontColourB="139" bgColourR="255" bgColourG="250" bgColourB="240">
<regEx description="Comment" expression="%\.*" colourR="0" colourG="153" colourB="0" style="Italic"/>
</editor>
</model>
<properties fontName="Monospaced" fontStyle="0" fontSize="12" selectionColourR="202" selectionColourG="225" selectionColourB="255" warningColourR="255" warningColourG="175" warningColourB="175" additionStrategy="warn" clearListOnLoad="true"/>
<simulator engine="prism" simultaneous="true" apmcStrategy="0" newPathAskDefault="true" renderAllValues="false"/>
<log fontName="monospaced" fontStyle="0" fontSize="12" selectionColourR="0" selectionColourG="0" selectionColourB="0" bgColourR="255" bgColourG="255" bgColourB="255" bufferLength="10000"/>
</options>
